sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t pwalus/docker-react .

script:
  - docker run -e CI=true pwalus/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-651109694713"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY